name: futuredragon
description: "FutureDragon—موقعي الخاص"
publish_to: "none"
version: 1.0.0+0
environment:
  sdk: ">=3.10.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  # google_mobile_ads: ^6.0.0
  google_mobile_ads: ^7.0.0
  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  # State management
  flutter_riverpod: ^3.0.3
  provider: ^6.1.5+1
  # Storage & preferences
  shared_preferences: ^2.5.4
  # Networking
  dio: ^5.9.0
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  # Media
  youtube_player_iframe: ^5.2.2
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.4.1
  wakelock_plus: ^1.4.0
  # video_player: ^2.10.0
  # better_player_plus: ^1.0.8
  # Auth & info
  google_sign_in: ^7.2.0
  package_info_plus: ^9.0.0
  # Navigation
  go_router: ^17.0.1
  # Localization & formatting
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^10.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/data/

flutter_icons:
  android: true
  image_path: "assets/icon/icon.png"